In [54]:
import pandas as pd
import numpy as np

In [2]:
events = pd.read_csv("athlete_events.csv")

In [4]:
events.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [26]:
#Avg age of Gold, Silver, Bronze, No Medals
#events.fillna("None", inplace=True)
events.groupby(by = "Medal")["Age"].mean()

Medal
Bronze    25.879210
Gold      25.901013
None      25.492289
Silver    25.996724
Name: Age, dtype: float64

In [37]:
#Which sports have the youngest winners on average? Which have the oldest?
#Ambiguous question here. Is winning just a gold medal or any medal? Let's assume winning is any medal.

events_medal = events.replace({"Medal": {"Bronze": "Medal", "Silver": "Medal", "Gold": "Medal"}}) #Grouping all medal values to just medal
events_medal.groupby(["Sport", "Medal"])['Age'].mean().unstack().sort_values("Medal") #Look at top 5, bottom 5

Medal                          Medal       None
Sport
Rhythmic Gymnastics        18.931818  18.688213
Swimming                   20.923356  20.511861
Diving                     22.264775  22.521323
Short Track Speed Skating  22.429577  22.889600
Boxing                     23.058002  23.054189
Gymnastics                 23.406493  22.669937
Taekwondo                  23.451389  24.244589
Ski Jumping                23.753623  23.308716
Synchronized Swimming      23.809302  21.917391
Figure Skating             24.020779  21.867655
Trampolining               24.033333  25.409836
Football                   24.159373  23.545774
Military Ski Patrol        24.250000  22.857143
Alpine Skiing              24.343458  23.146942
Rugby                      24.385965        NaN
Cycling                    24.595142  24.798681
Snowboarding               24.666667  24.842790
Table Tennis               24.720238  26.626966
Freestyle Skiing           24.931373  24.365269
Athletics                  25.020532  25.177761
Nordic Combined            25.103030  24.235043
Judo                       25.199269  25.351679
Weightlifting              25.278302  25.547981
Rugby Sevens               25.337838  26.280000
Basketball                 25.342301  25.318765
Speed Skating              25.374138  24.179697
Badminton                  25.380952  25.709077
Rowing                     25.565371  25.163282
Volleyball                 25.775026  24.947650
Hockey                     25.779559  25.691604
...                              ...        ...
Wrestling                  26.076680  25.733049
Baseball                   26.252976  26.233393
Handball                   26.349057  26.291100
Softball                   26.759777  26.023411
Lacrosse                   26.861111        NaN
Tennis                     26.887195  25.710373
Biathlon                   26.901961  26.499331
Modern Pentathlon          27.220430  26.280946
Cross Country Skiing       27.617268  25.855924
Golf                       27.782609  29.804233
Triathlon                  28.200000  27.851703
Racquets                   28.800000  28.000000
Fencing                    28.895930  28.464819
Skeleton                   28.933333  29.994012
Jeu De Paume               29.000000  33.750000
Cricket                    29.333333        NaN
Tug-Of-War                 29.538462  28.714286
Beach Volleyball           29.750000  29.030488
Bobsleigh                  29.848485  28.997297
Archery                    30.927900  27.441860
Croquet                    31.125000  36.714286
Motorboating               31.714286  34.750000
Sailing                    31.804255  29.941475
Curling                    33.302632  30.488746
Shooting                   33.449871  33.418816
Polo                       34.584615  37.280000
Equestrianism              35.371728  34.210547
Alpinism                   38.812500        NaN
Art Competitions           42.328947  46.087016
Roque                      53.333333        NaN

[66 rows x 2 columns]

In [44]:
#4. Who has won the most medals?
#Assumes names are spelled consistently

events_medal.groupby(["Name", "Medal"])['Medal'].count().unstack().sort_values("Medal", ascending=False)

Medal                                            Medal  None
Name
Michael Fred Phelps, II                           28.0   2.0
Larysa Semenivna Latynina (Diriy-)                18.0   1.0
Nikolay Yefimovich Andrianov                      15.0   9.0
Borys Anfiyanovych Shakhlin                       13.0  11.0
Takashi Ono                                       13.0  20.0
Ole Einar Bjrndalen                               13.0  14.0
Edoardo Mangiarotti                               13.0   1.0
Ryan Steven Lochte                                12.0   2.0
Birgit Fischer-Schmidt                            12.0   1.0
Paavo Johannes Nurmi                              12.0   NaN
Natalie Anne Coughlin (-Hall)                     12.0   NaN
Jennifer Elisabeth "Jenny" Thompson (-Cumpelik)   12.0   5.0
Sawao Kato                                        12.0  12.0
Dara Grace Torres (-Hoffman, -Minas)              12.0   1.0
Aleksey Yuryevich Nemov                           12.0   9.0
Aleksandr Vladimirovich Popov                     11.0  15.0
Matthew Nicholas "Matt" Biondi                    11.0   1.0
Mark Andrew Spitz                                 11.0   1.0
Viktor Ivanovych Chukarin                         11.0   5.0
Vra slavsk (-Odloilov)                            11.0   7.0
Carl Townsend Osburn                              11.0   5.0
Gary Wayne Hall, Jr.                              10.0   NaN
Vitaly Venediktovich Shcherbo                     10.0   6.0
Marit Bjrgen                                      10.0   9.0
Raymond Clarence "Ray" Ewry                       10.0   NaN
gnes Keleti-Srkny (Klein)                         10.0   4.0
Stefania Belmondo                                 10.0  12.0
Yang Yang                                         10.0  10.0
Gerard Theodor Hubert Van Innis                   10.0   1.0
Akinori Nakayama                                  10.0   6.0
...                                                ...   ...
va von Botond                                      NaN   1.0
va vri                                             NaN  12.0
van der Stoppen                                    NaN   1.0
variste Marius Fernand Prat                        NaN   1.0
ve Lamoureux                                       NaN   1.0
velyne Cloupet                                     NaN   1.0
velyne Imbert                                      NaN   1.0
velyne Lebret (-Renard)                            NaN   1.0
velyne lien                                        NaN   3.0
verson da Silva Teixeira                           NaN   2.0
verton dos Santos Lopes                            NaN   2.0
ystein Brten                                       NaN   1.0
ystein Carlsen (-Lund Carlsen)                     NaN   1.0
ystein Grdum                                       NaN   3.0
ystein Jarlsbo                                     NaN   2.0
ystein Mellerud                                    NaN   1.0
ystein Olsen                                       NaN   1.0
ystein Slettemark                                  NaN   2.0
yvind Berg                                         NaN   5.0
yvind Tveter                                       NaN   2.0
zcan Ediz                                          NaN   2.0
zdemir Akbal                                       NaN   2.0
zden Ezinler                                       NaN   1.0
zer Atei                                           NaN   3.0
zge Bayrak                                         NaN   1.0
zge Krdar emberci                                  NaN   1.0
zlem Kaya                                          NaN   2.0
zman Graud                                         NaN   1.0
zzet Safer                                         NaN   1.0
zzet nce                                           NaN   2.0

[134732 rows x 2 columns]

In [65]:
#5. What percentage of athletes have won medals?
#Filtering source = https://stackoverflow.com/a/38258528
len(events_medal.groupby(["Name", "Medal"])['Medal'].count().unstack()["Medal"][lambda x: x.notnull()])/ len(events_medal.groupby(["Name", "Medal"])['Medal'].count().unstack()["Medal"])

0.2093192411602292

In [73]:
#6. Which athlete has competed in the most number of events? The least?
events_medal.groupby(["Name", "Event"])['ID'].count().groupby("Name").sum().sort_values() #Big tie for least number of events

Name
  Gabrielle Marie "Gabby" Adcock (White-)     1
Lucien Laplace                                1
Lucien Lafert                                 1
Lucien Konter                                 1
Lucien Koch                                   1
Lucien Joseph Fontanarosa                     1
Lucien Johannes Claes                         1
Lucien Jean Londot                            1
Lucien Hugo Mamba-Schlick                     1
Lucien Henri "Luc" Decrop                     1
Lucien Hansen                                 1
Lucien Genot                                  1
Lucien Demuynck                               1
Lucien Delfour                                1
Lucien Dehoux                                 1
Lucien Debleyser                              1
Lucien De Brauwere                            1
Lucien Cujean                                 1
Lucien C. N. Boekmans                         1
Lucien Bottin                                 1
Lucien Marinier                               1
Lucien Michard                                1
Lucien Millet                                 1
Lucien Paul Nol Huteau                        1
Lucimara Silvestre da Silva                   1
Lucimar "Lcio" Ferreira da Silva              1
Lucilo de la Pea Lpez Trigo                   1
Lucille Mary Ash (-McClure, -Klee)            1
Lucile Virginie Madeleine Fain (Condren-)     1
Lucijan Kleva                                 1
                                             ..
Aleksander Rokosa                            24
Georg "Georges" Miez                         25
Gabriella Paruzzi                            25
Lee Ju-Hyeong                                25
Lars Jrgen Madsen                            26
Gustaf Eric Carlberg                         26
Fabian Hambchen                              26
Yang Wei                                     26
Aleksandr Vladimirovich Popov                26
Adrianus Egbert Willem "Arie" de Jong        27
Ole Einar Bjrndalen                          27
Miltiades Manno                              28
Ivan Joseph Martin Osiier                    29
Oksana Aleksandrovna Chusovitina             29
Michael Fred Phelps, II                      30
Yordan Yovchev Yovchev                       30
Karl Tore William Thoresson                  30
Alfred August "Al" Jochim                    31
Michel Mathiot                               31
Johann "Hans" Sauter                         31
Alfred James Munnings                        31
Andreas Wecker                               32
Alexandros Theofilakis                       32
Alfrd (Arnold-) Hajs (Guttmann-)             32
Jean Lucien Nicolas Jacoby                   32
Takashi Ono                                  33
Ioannis Theofilakis                          36
Joseph "Josy" Stoffel                        38
Heikki Ilmari Savolainen                     39
Robert Tait McKenzie                         58
Name: ID, Length: 134732, dtype: int64

In [75]:
#7. Which sports have athletes with the highest weight? The lowest?
#Answering using means, limited to athletes/observations who reported weight. appears to be in (KG)
events_medal.groupby("Sport")["Weight"].mean().sort_values()

Sport
Rhythmic Gymnastics          48.760976
Synchronized Swimming        55.863529
Gymnastics                   56.916553
Trampolining                 59.322148
Figure Skating               59.543651
Diving                       60.572741
Triathlon                    61.817490
Short Track Speed Skating    64.310484
Table Tennis                 64.956449
Ski Jumping                  65.079014
Boxing                       65.249890
Cross Country Skiing         65.877670
Biathlon                     66.631419
Nordic Combined              66.909560
Freestyle Skiing             67.026835
Softball                     67.471655
Equestrianism                67.803975
Taekwondo                    68.007475
Badminton                    68.171439
Hockey                       69.169909
Athletics                    69.249287
Snowboarding                 69.549189
Archery                      70.011135
Speed Skating                70.026352
Cycling                      70.067944
Modern Pentathlon            70.279540
Football                     70.446834
Swimming                     70.588492
Tennis                       70.802291
Golf                         71.194444
                               ...
Wrestling                    75.495570
Sailing                      75.975154
Canoeing                     76.492615
Lacrosse                     76.714286
Motorboating                 77.000000
Luge                         77.264151
Rugby                        77.533333
Weightlifting                78.726663
Judo                         78.759867
Volleyball                   78.900214
Rugby Sevens                 78.939799
Beach Volleyball             79.089219
Rowing                       80.035863
Ice Hockey                   80.810364
Handball                     81.497151
Water Polo                   84.566446
Baseball                     85.707792
Basketball                   85.777053
Bobsleigh                    89.250678
Tug-Of-War                   95.615385
Aeronautics                        NaN
Alpinism                           NaN
Basque Pelota                      NaN
Cricket                            NaN
Croquet                            NaN
Jeu De Paume                       NaN
Military Ski Patrol                NaN
Polo                               NaN
Racquets                           NaN
Roque                              NaN
Name: Weight, Length: 66, dtype: float64

In [106]:
#8. What's the average age of Gymnastics winners before 1970? After 1970?
#Source: https://stackoverflow.com/a/47291304
events_1970 = events_medal.replace({"Year": {x:"After" if x > 1970 else "Before" for x in range(2017)}})
events_1970.groupby(["Year", "Medal", "Sport"])["Age"].mean().unstack()["Gymnastics"].unstack()

Medal       Medal       None
Year
After   20.665525  20.853360
Before  25.237986  24.791752

#Which sport has the most predictability of getting a medal given the sex, age, height, weight, and team of an athlete, out of Gymnastics, Swimming, and Wrestling.

For this, I would approach it by building a simple logistic regression model that controlled for sex, age, height, weight, and team in predicting whether or not a case would medal. I would then include dummy variables for whether or not the sport is Gymnastics, etc. I would compare how the different sport dummies increase/decrease the probability of medaling. The sport to offer the greatest probability on average would have the most predictability given the parameters.